### PR TITLE
Add Puppet 8 support

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
I wonder why Archlinux fails. Perhaps it's missing some facts? Also quite weird that it fails to load BSD.

**Comment by ekohl** [comment]
It's actually this part: https://github.com/puppetlabs/puppet/blob/c4c07ee6aa088324d9d8612c9fdb1daed75a739d/lib/puppet/provider/service/init.rb#L25-L26
So it suggests the `os.name` or `os.family` fact is missing.

**Comment by ekohl** [comment]
https://github.com/puppetlabs/puppet/pull/9082

**Comment by jhoblitt** [comment]
rebased on current master.

**Review by jhoblitt — APPROVED** [review]

**Pull request merged**
